apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000


#kubectl -n guler apply -f .\kubernetes\services.yaml
#kubectl -n guler get svc
#kubectl -n guler describe svc example-service
